# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Cutestrap
email: tylerwchilds@gmail.com
description: >
  A pure CSS framework with vertical rhythm, consistent form fields and a dead simple grid.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.cutestrap.com" # the base hostname & protocol for your site
tagline: A strong, independent CSS Framework. Only 2.7KB minified & gzipped.
cache_buster: 20190923_0
# Build settings
markdown: kramdown
